### ISSUE TITLE
Editor funktioniert nicht

### ISSUE THREAD

**Issue by jnlmmln** [Spikeone/PowerHeroes#14]
Mann kann nur die Breite bis 128 erhöhen.
Keine Möglichkeit für weiter oder abbrechen.

![image](https://user-images.githubusercontent.com/12248371/65363885-81645580-dc0e-11e9-80bc-ce758c2597a4.png)

**Comment by Spikeone** [comment]
This issue has been fixed in v0.3.6 - sadly the download page still linked to v0.3.5
