### ISSUE TITLE
Fenster ändert die Position beim Vergrößern/Verkleinern

### ISSUE THREAD

**Issue by jnlmmln** [Spikeone/PowerHeroes#15]
Beim ändern der Fenstergröße mit der Maus ändert sich beim loslassen der Taste auch die Fensterposition.
Fällt bei schnellen und großen Änderungen stärker auf.

Beispiel: Fenster in der rechten unteren Ecke platzieren und an der linken oberen Ecke vergrößern. Beim loslassen springt das Fenster weiter nach rechts unten.

**Comment by Spikeone** [comment]
This is caused by the windows resizing API. The game maintains the correct aspect ratio, so if you resize the window and the width change is larger than the height change, the height change will be increased by the missing amount. This leads to the behavior you described.
