### ISSUE TITLE
Fensterposition speichern

### ISSUE THREAD

**Issue by jnlmmln** [Spikeone/PowerHeroes#16]
Die letzte Fensterposition speichern und beim Starten wiederherstellen.

**Comment by Spikeone** [comment]
I already added this feature - sadly positioning a window from within powershell is only possible by DLL imports and setting a window position which requires the screen resolution (if changed).

All together leading to a massive overhead which I wont add (need to stay below 1.44MB).

**Comment by Spikeone** [comment]
@Lock-up this is fixed in Version 0.5.2
