### ISSUE TITLE
Markiertes Feld - Cursor Position

### ISSUE THREAD

**Issue by jnlmmln** [Spikeone/PowerHeroes#18]
Das markierte Feld passt nicht zur Cursor Position, siehe Screenshot.
Fällt bei kleinerer Fenstergröße stärker auf!

![image](https://user-images.githubusercontent.com/12248371/65364128-07cd6700-dc10-11e9-8f8f-f991e47edae1.png)

**Comment by Spikeone** [comment]
Using an extreme tiny resolution I cant reproduce this issue. Please download v0.3.6 and check if this problem persists.

![image](https://user-images.githubusercontent.com/1276342/65373610-2e2aeb00-dc80-11e9-99d4-19ae09af793d.png)
