### ISSUE TITLE
Editor: Show selected color under mouse

### ISSUE THREAD

**Issue by jnlmmln** [Spikeone/PowerHeroes#2]
Vielen Dank für deine Arbeit.

Show a preview of the selected color while moving the mouse over the map.

**Comment by Spikeone** [comment]
Könntest du bitte etwas genauer ausführen was du meinst?

**Comment by jnlmmln** [comment]
Ich meine während man mit der Maus über der Karte ist man eine Vorschau sieht was passiert wenn man jetzt Linksklick machen würde.

**Comment by Spikeone** [comment]
I think that'd need some performance. As in my opinion and experience good mapeditors know how to use their editor tool, I'd keep it as a wish for now.
Maybe when the editor is finished this could be added.

**Comment by Spikeone** [comment]
Press "P" when using the editor to toggle between preview and cursor mode, hope that helps
